### ISSUE TITLE
bulk_metaDigitise

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaDigitise#19]
For like data, merge these datasets into a list of four based on the types of plots

**Comment by daniel1noble** [comment]
More details on this point. When type is "diff" then group all like figures and condense these into a list of four (mean_se, scatterplot, histogram and boxplot) condensing the same data types into the relevant list slots.

**Comment by joelpick** [comment]
At the moment `bulk_metaDigitise` doesn't output anything when file type are different. I think that this is becasue it assumes the `processed_data` is the same for all plot types, but it is very different for the four plots. I think this an issue with `extract_digitised`? Otherwise `bulk_metaDigitise` seems to be working beautifully

**Comment by daniel1noble** [comment]
Yes, I’ve not tested this so it likely just needs to some tweaking in `extract_digitised`. I need to fix a few small bugs in this function anyway.

**Comment by daniel1noble** [comment]
I think I've fixed this now
