### ISSUE TITLE
bulk_digitise

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaDigitise#6]
For folder with different style graphs, ideally, it would be best to load image and then specify the type first before data collection as opposed to specifying without knowing what comes next. Needs to modify `extract_points` function @joelpick

**Comment by joelpick** [comment]
the `specify_type` function is now within `extract_points` (now renamed to `metaDigitise`). Need to update `bulk_digitise` to reflect this @daniel1noble

**Comment by joelpick** [comment]
problem is now that because `specify_type' is assigned in the function, the same and diff in `bulk_digitise' now won't work. Need to alter this. Maybe can have if the plot_type argument is empty in `metaDigitise', then ask the user what plot_type it is. Then can specify in advance using same in `bulk_digitise'

**Comment by daniel1noble** [comment]
Will try and look at this a little later and fix. We need model build ready fro Friday! :) Stop breaking things @joelpick ;P

**Comment by joelpick** [comment]
This this is all resolved / covered in other issues
